name: "Teable Community Edition"
version: "1.0.0"
slug: "teable"
description: "Teable Community Edition - A no-code database running in Home Assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/yourusername/ha-teable-addon"
startup: "application"
boot: "auto"
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web interface for Teable"
options:
  database_url: "postgres://teable:teable@db:5432/teable"
schema: "public"
map:
  - "config:rw"
environment:
  DATABASE_URL: "{{ .options.database_url }}"
