---
name: Teable
version: 1.0.1
slug: teable
description: Home Assistant Add-on: teable
uart: true
url: https://github.com/x9132706292/hassos-addon-teable
panel_icon: mdi:file-table-box-outline
host_network: true
before: before
arch:
  - amd64
  - armv7
  - i386
boot: auto
map:
  - share:rw
  - addons:rw
  - ssl:ro
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web interface
options:
  REDIS_PASSWORD: ""
schema:
  REDIS_PASSWORD: password
