---
name: Redis
version: 1.0.1
slug: redis
description: Redis-server
uart: true
url: https://github.com/x9132706292/hassio-addon-redis
host_network: true
before: before
arch:
  - amd64
  - armv7
  - i386
boot: auto
map:
  - share:rw
  - addons:rw
  - ssl:ro
ports:
  6379/tcp: 6379
ports_description:
  6379/tcp: Web interface
options:
  REDIS_PASSWORD: ""
schema:
  REDIS_PASSWORD: password
