{
    "name": "Teable",
    "version": "dev",
    "slug": "teable",
    "description": "Home Assistant Add-on: teable",
    "startup": "services",
    "boot": "auto",
    "webui": "http://[HOST]:[PORT:3000]",
    "panel_icon": "mdi:cloud-sync",
    "ports": {
        "3000/tcp": 3000
    },
    "ports_description": {
        "3000/tcp": "Web interface"
    },
    "map": [
        "share:rw"
    ],
    "options": {
        # replace the default password
        "POSTGRES_PASSWORD: "replace_this_password"
        "REDIS_PASSWORD": "replace_this_password"
        "SECRET_KEY": "replace_this_secret_key"
 
        # replace the following with a publicly accessible address
        "PUBLIC_ORIGIN": "http://127.0.0.1:3000"
        
  
        # Postgres
        "POSTGRES_HOST": "localhost"
        "POSTGRES_PORT": "5432"
        "POSTGRES_DB": "teable"
        "POSTGRES_USER": "teable"
        "PUBLIC_DATABASE_PROXY": ""
        
        # Redis
        "REDIS_HOST": "teable-cache"
        "REDIS_PORT": "6379"
        "REDIS_DB": "0"
        
        # App
        "PRISMA_DATABASE_URL": "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
        "BACKEND_CACHE_PROVIDER": "redis"
        "BACKEND_CACHE_REDIS_URI": "redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}"

    },
    "schema": {
    },
    "arch": [
        "aarch64",
        "amd64",
    ],
    "image": "ghcr.io/teableio/teable:latest"
}
