{
    "name": "Teable",
    "version": "dev",
    "slug": "teable",
    "description": "Home Assistant Add-on: teable",
    "startup": "services",
    "boot": "auto",
    "webui": "http://[HOST]:[PORT:3000]",
    "panel_icon": "mdi:cloud-sync",
    "ports": {
        "3000/tcp": 3000
    },
    "ports_description": {
        "3000/tcp": "Web interface"
    },
    "map": [
        "share:rw"
    ],
    "options": {
        "MYSQL_DATABASE": "nextcloud",
        "MYSQL_USER": "nextcloud",
        "MYSQL_PASSWORD": "",
        "MYSQL_HOST": "addon_core_mariadb",
        "NEXTCLOUD_ADMIN_USER": "hassio",
        "NEXTCLOUD_ADMIN_PASSWORD": "",
        "NEXTCLOUD_TRUSTED_DOMAINS": "homeassistant.local",
        "TRUSTED_PROXIES": "127.0.0.1 172.30.33.0/24 192.168.1.1"
    },
    "schema": {
    },
    "arch": [
        "aarch64",
        "amd64",
    ],
    "image": "ghcr.io/teableio/teable:latest"
}
